import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className = "w-full h-full bg-gradient-to-b from-blue-200 to-red-200">
          <div className = "h-24">
          <Navbar />
          </div>
          <div className = "h-[calc(100vh - 6rem)]">
          {children}
          </div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
